# Generated by Django 2.2.6 on 2019-11-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191101_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_meme', 'Set book as a meme'),)},
        ),
    ]
