# Generated by Django 2.2.6 on 2019-11-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191101_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_yee', 'Set book as a meme'),)},
        ),
    ]
